import React from 'react'
import Link from 'next/link';
import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import logoPic from '../../public/images/mh_logo.png'
import Image from 'next/image'

const Header = () => {
    return (
        <div>
            <Head>
                <title>Melbourn Handyman</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div class={styles.logo}>
                <Link href="/">
                    <a>
                        <Image
                            src={logoPic}
                            width={266}
                            height={133}
                        />
                    </a>
                </Link>
            </div>
        </div>
    );
}

export default Header
