import Head from 'next/head'
import Image from 'next/image'
import { Carousel } from '../src/components'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import logoPic from '../public/images/mh_logo.png'
import Link from 'next/link';

const Bathroom = ({posts, error}) => {
  
  const myLoader=({src})=>{
    return src;
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Melbourn Handyman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div class={styles.logo}>
        <Link href="/">
          <Image
              src={logoPic}
              width={266}
              height={133}
            />
        </Link>
        </div>
        <nav>
            <ul class={styles.ul}>
              <Link href="/kitchen">
                <a>
                  <li class={styles.li} key={1}>Kitchen</li>
                </a>
              </Link>
              <Link href="/bathroom">
                 <a>
                  <li class={styles.li} key={2}>Bathroom</li>
                 </a>
              </Link>
              <Link href="/painting">
                 <a>
                  <li class={styles.li} key={4}>Painting</li>
                 </a>
              </Link>
              <Link href="/fence">
                 <a>
                  <li class={styles.li} key={5}>Fence</li>
                 </a>
              </Link>
            </ul>
        </nav>
        <main className={styles.main}>
           <h1>Bathroom</h1>
      </main>

      <footer className={styles.footer}>
       
          Copyright by Melbourne Handyman 
       
      </footer>
    </div>
  )
}


export async function getServerSideProps({params,req,res,query,preview,previewData,resolvedUrl,locale,locales,defaultLocale}) {
  if (query.text) {
    return { redirect: { destination: '/', permanent: false, },}
  }
  const data = await fetch(`${process.env.HOST}/api/posts`);
  const posts = await data.json();
  if (!data) {
    return {notFound: true,}
  }  
  return { props: { posts } }
}


export default Bathroom;